---
title: "UCanFeel Descriptives"
author: "Anne Margit"
date: "5/12/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F}
load("data_ucanfeel.Rdata")
```

```{r, message=F}
library(dplyr)
library(skimr)
library(tidyverse)
library(stringr)
library(papaja)
library(reshape2)   
library(ggplot2)
```

Aantal participanten per schooljaar
```{r, message=F}
pp_school <- data_ucanfeel %>%
  group_by(schooljaar) %>%
  summarise(n_id = n_unique(id))
``` 

```{r, message=F}
apa_table(pp_school, caption="Aantal participanten per schooljaar")
```

Gemiddelden en SDs schoolfactoren (tevredenheid etc) per schooljaar
```{r, message=F}
schoolfactoren <- data_ucanfeel %>%
  group_by(schooljaar) %>%
  summarise(across(TR:AE_Stress, .fns=list(Mean = mean, SD = sd), na.rm=TRUE,
                   .names="{col}_{fn}"))

schoolfactoren <- schoolfactoren %>%
  mutate(across(2:11, round, 2))
```
TR = Teacher relationships
SC = School connectedness 
AS = Academic support
OD = Order and discipline
ASF = Academic satisfaction

```{r, message=F}
apa_table(schoolfactoren, caption="Schoolfactoren (M, SD) per schooljaar")
```

```{r, message=F}
school_bp <- data_ucanfeel %>%
  select(id, TR, SC, AS, OD, ASF, AE_Stress) %>%
  melt()

ggplot(school_bp, aes(x = variable, y = value)) + 
  geom_boxplot()
```

Gemiddelden en SDs angst and depressie en life satisfaction per schooljaar
```{r, message=F}
angst_dep_lifesat <- data_ucanfeel %>%
  group_by(schooljaar) %>%
  summarise(across(lifesat:rcads_dep, .fns=list(Mean = mean, SD = sd), na.rm=TRUE,
                   .names="{col}_{fn}"))

angst_dep_lifesat <- angst_dep_lifesat %>%
  mutate(across(2:7, round, 2))
```

```{r, message=F}
apa_table(angst_dep_lifesat, caption="Angst and depressie per schooljaar")
```

Jongens vs meisjes (jongen = 0, meisje = 1, anders = 2)
```{r, message=F}
angst_dep_geslacht <- data_ucanfeel %>%
  group_by(geslacht) %>%
  summarise(across(lifesat:rcads_dep, .fns=list(Mean = mean, SD = sd), na.rm=TRUE,
                   .names="{col}_{fn}"))

angst_dep_geslacht <- angst_dep_geslacht %>%
  mutate(across(2:7, round, 2))
```

```{r, message=F}
apa_table(angst_dep_geslacht, caption="Angst and depressie per geslacht")
```


```{r, message=F}
data_ucanfeel %>% skim("geslacht", "leeftijd", "schooljaar", "eenhuis", "niveau_nu",
                       "TR", "SC", "AS", "OD", "ASF", "AE_Stress",
                       "happy", "rcads_anx", "rcads_dep", "distress_precorona", "distress_nu",
                       "vrienden_klas", "vrienden_school", "pest_freq")
```
